/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import ReadXml.Dish;
import ReadXml.Dishes;
import ReadXml.Restaurant;
import ReadXml.Table;
import ReadXml.Tables;
import ReadXml.User;
import ReadXml.Users;
import com.sun.glass.events.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import java.awt.Color;

public class ClientWindow extends javax.swing.JFrame {

    private Restaurant r;
    private Restaurant x = new Restaurant();
    private User v ;
    private Table g = null;
  private static List<Table> reserved= new ArrayList<>();
    private static List<Dish> ordered= new ArrayList<>();
    private static List<User> customers= new ArrayList<>();
    public static List <Double> totales = new ArrayList();
  
           
    
    
    

    public ClientWindow(Restaurant r, User u) {
  
        initComponents();
        this.r = r;
        this.v = u;
    }

    private ClientWindow() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jChecGrilled = new javax.swing.JCheckBox();
        jCheckMushroom = new javax.swing.JCheckBox();
        jCheckBeef = new javax.swing.JCheckBox();
        jTextGrilled = new javax.swing.JTextField();
        jTextMushroom = new javax.swing.JTextField();
        jTextBeef = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jCheckSalad = new javax.swing.JCheckBox();
        jCheckFries = new javax.swing.JCheckBox();
        jTextSalad = new javax.swing.JTextField();
        jTextFries = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jCheckMolten = new javax.swing.JCheckBox();
        jCheckPie = new javax.swing.JCheckBox();
        jTextPie = new javax.swing.JTextField();
        jTextMolten = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextTax = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextSubTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButtonTotal = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextTotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client Window ");
        setBackground(java.awt.Color.white);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/2020-04-04 (3).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel2.setText("Welcome to Budget Bytes reservation page");

        jLabel3.setText("Please fill in the details of your desired table:");

        jLabel4.setText("Enter the number of seats :");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Smoking", "Non smoking" }));

        jLabel15.setText("Time of reservation");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "am", "pm" }));

        jButton1.setText("Confirm reservation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));

        jLabel5.setText("Main Course");

        jChecGrilled.setText("Grilled Chicken");
        jChecGrilled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChecGrilledActionPerformed(evt);
            }
        });

        jCheckMushroom.setText("Mushroom Soup");
        jCheckMushroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckMushroomActionPerformed(evt);
            }
        });

        jCheckBeef.setText("Beef Steak");
        jCheckBeef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBeefActionPerformed(evt);
            }
        });

        jTextGrilled.setText("0");
        jTextGrilled.setEnabled(false);
        jTextGrilled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGrilledActionPerformed(evt);
            }
        });
        jTextGrilled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextGrilledKeyTyped(evt);
            }
        });

        jTextMushroom.setText("0");
        jTextMushroom.setEnabled(false);
        jTextMushroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMushroomActionPerformed(evt);
            }
        });
        jTextMushroom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextMushroomKeyTyped(evt);
            }
        });

        jTextBeef.setText("0");
        jTextBeef.setEnabled(false);
        jTextBeef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBeefActionPerformed(evt);
            }
        });
        jTextBeef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextBeefKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckMushroom)
                            .addComponent(jChecGrilled)
                            .addComponent(jCheckBeef))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextBeef, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextGrilled, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMushroom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChecGrilled)
                    .addComponent(jTextGrilled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckMushroom)
                    .addComponent(jTextMushroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBeef)
                    .addComponent(jTextBeef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 3, true));

        jLabel6.setText("Appetizers");

        jCheckSalad.setText("Greek Salad");
        jCheckSalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckSaladActionPerformed(evt);
            }
        });

        jCheckFries.setText("Fried Potatoes");
        jCheckFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckFriesActionPerformed(evt);
            }
        });

        jTextSalad.setText("0");
        jTextSalad.setEnabled(false);
        jTextSalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSaladActionPerformed(evt);
            }
        });
        jTextSalad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextSaladKeyTyped(evt);
            }
        });

        jTextFries.setText("0");
        jTextFries.setEnabled(false);
        jTextFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFriesActionPerformed(evt);
            }
        });
        jTextFries.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFriesKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckSalad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextSalad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckFries)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFries, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckSalad)
                    .addComponent(jTextSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckFries)
                    .addComponent(jTextFries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 50, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 3, true));

        jLabel7.setText("Dessert");

        jCheckMolten.setText("Molten Cake");
        jCheckMolten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckMoltenActionPerformed(evt);
            }
        });

        jCheckPie.setText("Apple Pie");
        jCheckPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckPieActionPerformed(evt);
            }
        });

        jTextPie.setText("0");
        jTextPie.setEnabled(false);
        jTextPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPieActionPerformed(evt);
            }
        });
        jTextPie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPieKeyTyped(evt);
            }
        });

        jTextMolten.setText("0");
        jTextMolten.setEnabled(false);
        jTextMolten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMoltenActionPerformed(evt);
            }
        });
        jTextMolten.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextMoltenKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextPie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckMolten)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextMolten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jCheckPie)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextMolten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckMolten))
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jCheckPie)
                    .addContainerGap(75, Short.MAX_VALUE)))
        );

        jLabel8.setText("Payment Method");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debut Card", "Master Card", "Visa Card" }));

        jLabel11.setText("Tax");

        jTextTax.setEditable(false);

        jLabel12.setText("L.E");

        jTextSubTotal.setEditable(false);
        jTextSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSubTotalActionPerformed(evt);
            }
        });

        jLabel10.setText("Sub Total");

        jLabel13.setText("L.E");

        jButton3.setText("Log out ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonTotal.setText("Total");
        jButtonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTotalActionPerformed(evt);
            }
        });

        jButton4.setText("Save order");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setText("Total");

        jTextTotal.setEditable(false);

        jLabel14.setText("L.E");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonTotal))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(25, 25, 25)
                                            .addComponent(jTextTotal))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGap(49, 49, 49)
                                            .addComponent(jTextTax, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                                .addComponent(jButton3))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton1)
                                                .addComponent(jLabel4))
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel15)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addGap(32, 32, 32)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(46, 46, 46)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jButton3)))
                            .addGap(32, 32, 32)
                            .addComponent(jLabel14))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jTextTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jTextSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char iNumber = evt.getKeyChar();
        if (!Character.isDigit(iNumber) || iNumber == KeyEvent.VK_BACKSPACE || iNumber == KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int n = Integer.parseInt(jTextField1.getText());
        String s = (String) jComboBox1.getSelectedItem();
        boolean so;
        if (s.equalsIgnoreCase("Smoking")) {
            so = true;
        } else {
            so = false;
        }
        List<Table> t = r.getTa().getT();
        for (int i = 0; i < t.size(); i++) {
            if (t.get(i).getNumberOfSeats() == n && t.get(i).isSomking() == so) {
                try {
                    g= t.get(i);
                    g.setTimeOfReservation(jTextField2.getText()+jComboBox3.getSelectedItem());
                    reserved.add(g);
                    t.remove(g);

                }
                catch(NullPointerException e)
                {
                    System.out.println("Error casting table");

                }
                jLabel16.setText("Reservation completed");
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jChecGrilledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChecGrilledActionPerformed

        if (jChecGrilled.isSelected()) {
            jTextGrilled.setEnabled(true);
            jTextGrilled.requestFocus();
            jTextGrilled.setText("");
            Dish d = new Dish();
            d.setName(jChecGrilled.getText());
            d.setPrice(75);
            d.setType("Main Course");
            d.setTax(0.15);
            ordered.add(d);

        } else {
            jTextGrilled.setEnabled(false);
            jTextGrilled.setText("0");
        }
    }//GEN-LAST:event_jChecGrilledActionPerformed

    private void jCheckMushroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckMushroomActionPerformed
        if (jCheckMushroom.isSelected()) {
            jTextMushroom.setEnabled(true);
            jTextMushroom.requestFocus();
            jTextMushroom.setText("");
            Dish d = new Dish();
            d.setName(jCheckMushroom.getText());
            d.setPrice(60);
            d.setType("Main Course");
            d.setTax(0.15);
            ordered.add(d);
        } else {
            jTextMushroom.setEnabled(false);
            jTextMushroom.setText("0");

        }
    }//GEN-LAST:event_jCheckMushroomActionPerformed

    private void jCheckBeefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBeefActionPerformed
        if (jCheckBeef.isSelected()) {
            jTextBeef.setEnabled(true);
            jTextBeef.requestFocus();
            jTextBeef.setText("");
            Dish d = new Dish();
            d.setName(jCheckBeef.getText());
            d.setPrice(80);
            d.setType("Main Course");
            d.setTax(0.15);
            ordered.add(d);
        } else {
            jTextBeef.setEnabled(false);
            jTextBeef.setText("0");
        }
    }//GEN-LAST:event_jCheckBeefActionPerformed

    private void jTextGrilledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGrilledActionPerformed

    }//GEN-LAST:event_jTextGrilledActionPerformed

    private void jTextGrilledKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextGrilledKeyTyped
        char iNumber = evt.getKeyChar();
        if (!Character.isDigit(iNumber) || iNumber == KeyEvent.VK_BACKSPACE || iNumber == KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextGrilledKeyTyped

    private void jTextMushroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMushroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMushroomActionPerformed

    private void jTextMushroomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextMushroomKeyTyped
        char iNumber = evt.getKeyChar();
        if (!Character.isDigit(iNumber) || iNumber == KeyEvent.VK_BACKSPACE || iNumber == KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextMushroomKeyTyped

    private void jTextBeefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBeefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBeefActionPerformed

    private void jTextBeefKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBeefKeyTyped
        char iNumber = evt.getKeyChar();
        if (!Character.isDigit(iNumber) || iNumber == KeyEvent.VK_BACKSPACE || iNumber == KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextBeefKeyTyped

    private void jCheckSaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckSaladActionPerformed
        if (jCheckSalad.isSelected()) {
            jTextSalad.setEnabled(true);
            jTextSalad.requestFocus();
            jTextSalad.setText("");
            Dish d = new Dish();
            d.setName(jCheckSalad.getText());
            d.setPrice(35);
            d.setType("Appetizer");
            d.setTax(0.1);
            ordered.add(d);
        } else {
            jTextSalad.setEnabled(false);
            jTextSalad.setText("0");
        }
    }//GEN-LAST:event_jCheckSaladActionPerformed

    private void jCheckFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckFriesActionPerformed
        if (jCheckFries.isSelected()) {
            jTextFries.setEnabled(true);
            jTextFries.requestFocus();
            Dish d = new Dish();
            d.setName(jCheckFries.getText());
            d.setPrice(30);
            d.setType("Appetizer");
            d.setTax(0.1);
            ordered.add(d);
        } else {
            jTextFries.setEnabled(false);
            jTextFries.setText("0");
        }
    }//GEN-LAST:event_jCheckFriesActionPerformed

    private void jTextSaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSaladActionPerformed

    }//GEN-LAST:event_jTextSaladActionPerformed

    private void jTextSaladKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSaladKeyTyped
        char iNumber = evt.getKeyChar();
        if (!Character.isDigit(iNumber) || iNumber == KeyEvent.VK_BACKSPACE || iNumber == KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextSaladKeyTyped

    private void jTextFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFriesActionPerformed

    private void jTextFriesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFriesKeyTyped
        char iNumber = evt.getKeyChar();
        if (!Character.isDigit(iNumber) || iNumber == KeyEvent.VK_BACKSPACE || iNumber == KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFriesKeyTyped

    private void jCheckMoltenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckMoltenActionPerformed
        if (jCheckMolten.isSelected()) {
            jTextMolten.setEnabled(true);
            jTextMolten.requestFocus();
            jTextMolten.setText("");
            Dish d = new Dish();
            d.setName(jCheckMolten.getText());
            d.setPrice(60);
            d.setType("Dessert");
            d.setTax(0.2);
            ordered.add(d);
        } else {
            jTextMolten.setEnabled(false);
            jTextMolten.setText("0");
        }
    }//GEN-LAST:event_jCheckMoltenActionPerformed

    private void jCheckPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckPieActionPerformed
        if (jCheckPie.isSelected()) {
            jTextPie.setEnabled(true);
            jTextPie.requestFocus();
            jTextPie.setText("");
            Dish d = new Dish();
            d.setName(jCheckPie.getText());
            d.setPrice(60);
            d.setType("Dessert");
            d.setTax(0.2);
            ordered.add(d);
        } else {
            jTextPie.setEnabled(false);
            jTextPie.setText("0");
        }
    }//GEN-LAST:event_jCheckPieActionPerformed

    private void jTextPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPieActionPerformed

    private void jTextPieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPieKeyTyped
        char iNumber = evt.getKeyChar();
        if (!Character.isDigit(iNumber) || iNumber == KeyEvent.VK_BACKSPACE || iNumber == KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextPieKeyTyped

    private void jTextMoltenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMoltenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMoltenActionPerformed

    private void jTextMoltenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextMoltenKeyTyped
        char iNumber = evt.getKeyChar();
        if (!Character.isDigit(iNumber) || iNumber == KeyEvent.VK_BACKSPACE || iNumber == KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextMoltenKeyTyped

    private void jTextSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSubTotalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int y = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to log out ?\n Please make sure "
            + " you have saved your order");
        if (y == 0) {
            LoginWindow z = null;
            try {
                z = new LoginWindow();
            } catch (JAXBException ex) {
                Logger.getLogger(ClientWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            z.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalActionPerformed
        int grilledPrice = 75;
        int mushroomPrice = 60;
        int beefPrice = 80;
        int saladPrice = 35;
        int friesPrice = 30;
        int piePrice = 50;
        int moltenPrice = 60;

        if (jChecGrilled.isSelected()) {

            int q = Integer.parseInt(jTextGrilled.getText());
            grilledPrice = grilledPrice * q;

        } else {
            grilledPrice = 0;
        }
        if (jCheckBeef.isSelected()) {
            int q = Integer.parseInt(jTextBeef.getText());
            beefPrice = beefPrice * q;

        } else {
            beefPrice = 0;
        }
        if (jCheckFries.isSelected()) {
            int q = Integer.parseInt(jTextFries.getText());
            friesPrice = friesPrice * q;

        } else {
            friesPrice = 0;
        }
        if (jCheckMolten.isSelected()) {
            int q = Integer.parseInt(jTextMolten.getText());
            moltenPrice = moltenPrice * q;

        } else {
            moltenPrice = 0;
        }
        if (jCheckMushroom.isSelected()) {
            int q = Integer.parseInt(jTextMushroom.getText());
            mushroomPrice = mushroomPrice * q;

        } else {
            mushroomPrice = 0;
        }
        if (jCheckPie.isSelected()) {
            int q = Integer.parseInt(jTextPie.getText());
            piePrice = piePrice * q;

        } else {
            piePrice = 0;
        }
        if (jCheckSalad.isSelected()) {
            int q = Integer.parseInt(jTextSalad.getText());
            saladPrice = saladPrice * q;

        } else {
            saladPrice = 0;
        }

        int subTotal = grilledPrice + beefPrice + friesPrice + moltenPrice + mushroomPrice + piePrice + saladPrice;
        String s = Integer.toString(subTotal);
        jTextSubTotal.setText(s);
        double Tax = (grilledPrice) * 0.15 + (beefPrice) * 0.15 + (friesPrice) * 0.1 + (moltenPrice) * 0.2
        + (mushroomPrice) * 0.15 + (piePrice) * 0.2 + (saladPrice) * 0.1;
        String c = Double.toString(Tax);
        jTextTax.setText(c);
        double total = Tax + subTotal;
        totales.add(total);
        for (int i = 0; i <totales.size(); i++) {
            System.out.println(totales.get(i));
        }
        String b = Double.toString(total);
        jTextTotal.setText(b);
    }//GEN-LAST:event_jButtonTotalActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Tables taken = new Tables();
        taken.setT(reserved);
        Dishes eaten = new Dishes();
        eaten.setDi(ordered);
        customers.add(v);
        Users cust = new Users();
        cust.setUsers(customers);
        x.setD(eaten);
        x.setTa(taken);
        x.setU(cust);
        try {
            JAXBContext jax = JAXBContext.newInstance(Dishes.class);
            Marshaller u = jax.createMarshaller();
            u.marshal(eaten, new File("Dishes.xml"));

        } catch (JAXBException ex) {
            Logger.getLogger(ClientWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

        try
        {
            JAXBContext jaxbContext = JAXBContext.newInstance(Tables.class);
            Marshaller jaxbMarshaller = jaxbContext.createMarshaller();
            jaxbMarshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
            File file = new File("Save.xml");

            try {
                new FileOutputStream(file, true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ClientWindow.class.getName()).log(Level.SEVERE, null, ex);
            }

            jaxbMarshaller.marshal(taken, file);
        }
        catch (JAXBException e)
        {
            e.printStackTrace();
        }
        try {
            JAXBContext jax = JAXBContext.newInstance(Users.class);
            Marshaller u = jax.createMarshaller();
            u.marshal(cust, new File("Users.xml"));

        } catch (JAXBException ex) {
            Logger.getLogger(ClientWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientWindow().setVisible(true);
                
            }
        });
    }

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonTotal;
    private javax.swing.JCheckBox jChecGrilled;
    private javax.swing.JCheckBox jCheckBeef;
    private javax.swing.JCheckBox jCheckFries;
    private javax.swing.JCheckBox jCheckMolten;
    private javax.swing.JCheckBox jCheckMushroom;
    private javax.swing.JCheckBox jCheckPie;
    private javax.swing.JCheckBox jCheckSalad;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextBeef;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFries;
    private javax.swing.JTextField jTextGrilled;
    private javax.swing.JTextField jTextMolten;
    private javax.swing.JTextField jTextMushroom;
    private javax.swing.JTextField jTextPie;
    private javax.swing.JTextField jTextSalad;
    private javax.swing.JTextField jTextSubTotal;
    private javax.swing.JTextField jTextTax;
    private javax.swing.JTextField jTextTotal;
    // End of variables declaration//GEN-END:variables
}
